### ISSUE TITLE
JS error after upgrading 0.0.18 to 1.1.3

### ISSUE THREAD

**Issue by jaimeiniesta** [mirego/telemetry_ui#9]
Hi, after upgrading to 1.1.3 I'm getting this JS error, both in Firefox and Google Chrome, and the charts don't render:

<img width="565" alt="Captura de pantalla 2022-12-02 a las 19 30 46" src="https://user-images.githubusercontent.com/2629/205361553-60ac4109-de3e-47e4-9248-89bb13941baa.png">

```
Uncaught SyntaxError: missing ) after argument list
metrics:108 Uncaught TypeError: window.drawChart is not a function
    at HTMLDocument.<anonymous> (metrics:108:12)
metrics:147 Uncaught TypeError: window.drawChart is not a function
    at HTMLDocument.<anonymous> (metrics:147:12)
metrics:186 Uncaught TypeError: window.drawChart is not a function
    at HTMLDocument.<anonymous> (metrics:186:12)
metrics:225 Uncaught TypeError: window.drawChart is not a function
    at HTMLDocument.<anonymous> (metrics:225:12)
metrics:264 Uncaught TypeError: window.drawChart is not a function
    at HTMLDocument.<anonymous> (metrics:264:12)
metrics:303 Uncaught TypeError: window.drawChart is not a function
    at HTMLDocument.<anonymous> (metrics:303:12)
metrics:342 Uncaught TypeError: window.drawChart is not a function
    at HTMLDocument.<anonymous> (metrics:342:12)
metrics:381 Uncaught TypeError: window.drawChart is not a function
    at HTMLDocument.<anonymous> (metrics:381:12)
```

We're on phoenix 1.6.12 and phoenix_live_view 0.18.2

**Comment by simonprev** [comment]
I don’t know if there is a way we can detect it and log a warning but this is a phoenix_live_reload bug that parses a body tag wrong. It is fixed in phoenix_live_reload 1.4.0 https://github.com/phoenixframework/phoenix_live_reload/issues/119

**Comment by jaimeiniesta** [comment]
Hey that was quick, thanks, it's fixed after the upgrade.
